// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using exercise.pizzashopapi.Data;

#nullable disable

namespace exercise.pizzashopapi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250127115428_changedmodels")]
    partial class changedmodels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("exercise.pizzashopapi.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Donald Trump"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Elvis Presley"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Barack Obama"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Oprah Winfrey"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Jimi Hendrix"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Mick Jagger"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Kate Winslet"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Charles Windsor"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Kate Middleton"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Audrey Hepburn"
                        });
                });

            modelBuilder.Entity("exercise.pizzashopapi.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OrderTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PizzaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PizzaId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 2,
                            OrderTime = new DateTime(2023, 12, 25, 23, 0, 0, 0, DateTimeKind.Utc),
                            PizzaId = 2
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 3,
                            OrderTime = new DateTime(2023, 12, 26, 23, 0, 0, 0, DateTimeKind.Utc),
                            PizzaId = 3
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 4,
                            OrderTime = new DateTime(2023, 12, 27, 23, 0, 0, 0, DateTimeKind.Utc),
                            PizzaId = 4
                        },
                        new
                        {
                            Id = 4,
                            CustomerId = 5,
                            OrderTime = new DateTime(2023, 12, 28, 23, 0, 0, 0, DateTimeKind.Utc),
                            PizzaId = 5
                        },
                        new
                        {
                            Id = 5,
                            CustomerId = 6,
                            OrderTime = new DateTime(2023, 12, 29, 23, 0, 0, 0, DateTimeKind.Utc),
                            PizzaId = 6
                        },
                        new
                        {
                            Id = 6,
                            CustomerId = 7,
                            OrderTime = new DateTime(2023, 12, 30, 23, 0, 0, 0, DateTimeKind.Utc),
                            PizzaId = 7
                        },
                        new
                        {
                            Id = 7,
                            CustomerId = 8,
                            OrderTime = new DateTime(2023, 12, 31, 23, 0, 0, 0, DateTimeKind.Utc),
                            PizzaId = 8
                        },
                        new
                        {
                            Id = 8,
                            CustomerId = 9,
                            OrderTime = new DateTime(2024, 1, 1, 23, 0, 0, 0, DateTimeKind.Utc),
                            PizzaId = 9
                        },
                        new
                        {
                            Id = 9,
                            CustomerId = 10,
                            OrderTime = new DateTime(2024, 1, 2, 23, 0, 0, 0, DateTimeKind.Utc),
                            PizzaId = 10
                        },
                        new
                        {
                            Id = 10,
                            CustomerId = 1,
                            OrderTime = new DateTime(2024, 1, 3, 23, 0, 0, 0, DateTimeKind.Utc),
                            PizzaId = 1
                        },
                        new
                        {
                            Id = 11,
                            CustomerId = 2,
                            OrderTime = new DateTime(2024, 1, 4, 23, 0, 0, 0, DateTimeKind.Utc),
                            PizzaId = 2
                        },
                        new
                        {
                            Id = 12,
                            CustomerId = 3,
                            OrderTime = new DateTime(2024, 1, 5, 23, 0, 0, 0, DateTimeKind.Utc),
                            PizzaId = 3
                        },
                        new
                        {
                            Id = 13,
                            CustomerId = 4,
                            OrderTime = new DateTime(2024, 1, 6, 23, 0, 0, 0, DateTimeKind.Utc),
                            PizzaId = 4
                        },
                        new
                        {
                            Id = 14,
                            CustomerId = 5,
                            OrderTime = new DateTime(2024, 1, 7, 23, 0, 0, 0, DateTimeKind.Utc),
                            PizzaId = 5
                        },
                        new
                        {
                            Id = 15,
                            CustomerId = 6,
                            OrderTime = new DateTime(2024, 1, 8, 23, 0, 0, 0, DateTimeKind.Utc),
                            PizzaId = 6
                        },
                        new
                        {
                            Id = 16,
                            CustomerId = 7,
                            OrderTime = new DateTime(2024, 1, 9, 23, 0, 0, 0, DateTimeKind.Utc),
                            PizzaId = 7
                        },
                        new
                        {
                            Id = 17,
                            CustomerId = 8,
                            OrderTime = new DateTime(2024, 1, 10, 23, 0, 0, 0, DateTimeKind.Utc),
                            PizzaId = 8
                        },
                        new
                        {
                            Id = 18,
                            CustomerId = 9,
                            OrderTime = new DateTime(2024, 1, 11, 23, 0, 0, 0, DateTimeKind.Utc),
                            PizzaId = 9
                        },
                        new
                        {
                            Id = 19,
                            CustomerId = 10,
                            OrderTime = new DateTime(2024, 1, 12, 23, 0, 0, 0, DateTimeKind.Utc),
                            PizzaId = 10
                        },
                        new
                        {
                            Id = 20,
                            CustomerId = 1,
                            OrderTime = new DateTime(2024, 1, 13, 23, 0, 0, 0, DateTimeKind.Utc),
                            PizzaId = 1
                        });
                });

            modelBuilder.Entity("exercise.pizzashopapi.Models.Pizza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Pizzas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Vegan Cheese Tastic",
                            Price = 50m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pepperoni",
                            Price = 50m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Margherita",
                            Price = 50m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Hawaiian",
                            Price = 50m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Vegetarian",
                            Price = 50m
                        },
                        new
                        {
                            Id = 6,
                            Name = "Meat Lovers",
                            Price = 50m
                        },
                        new
                        {
                            Id = 7,
                            Name = "BBQ Chicken",
                            Price = 50m
                        },
                        new
                        {
                            Id = 8,
                            Name = "Buffalo",
                            Price = 50m
                        },
                        new
                        {
                            Id = 9,
                            Name = "Supreme",
                            Price = 50m
                        },
                        new
                        {
                            Id = 10,
                            Name = "Cheese & Pineapple",
                            Price = 50m
                        });
                });

            modelBuilder.Entity("exercise.pizzashopapi.Models.Order", b =>
                {
                    b.HasOne("exercise.pizzashopapi.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("exercise.pizzashopapi.Models.Pizza", "Pizza")
                        .WithMany()
                        .HasForeignKey("PizzaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Pizza");
                });
#pragma warning restore 612, 618
        }
    }
}
